source 'https://rubygems.org'

gem 'rails', '~>4.1'
gem 'active_model_serializers'

# 数据库
gem 'pg'

# Web 服务器
gem 'unicorn'

# 中间件
gem 'rack-cors', require: 'rack/cors'

# 上传
gem 'carrierwave'

group :development do
  gem 'hirb'
  gem 'spring'
  gem 'awesome_print'
  gem 'interactive_editor'
  gem 'quiet_assets'
end

group :test do
  gem 'minitest'
  gem 'minitest-rails'
end

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
